set shell := ["bash", "-cu"]

clean:
    rm -rf build

make:
    cmake -B build
    cmake --build build

test: make
    cd build && ctest -V

all: clean make test create-arduino-lib

create-arduino-lib:
    mkdir EventsManager
    cp app/* EventsManager
    cp outbound_adapters/* EventsManager
    cp inbound_adapters/* EventsManager
    tar -cvzf EventsManager.tar.gz EventsManager
    rm -rfv EventsManager
    mv EventsManager.tar.gz ~/Arduino/libraries/
    cd ~/Arduino/libraries && rm -rf EventsManager && tar -xvzf EventsManager.tar.gz && rm EventsManager.tar.gz

