version: "3.9"

services:
  mosquitto:
    image: docker.io/eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"   # websocket port
    volumes:
      - ./config:/mosquitto/config:Z
      - ./data:/mosquitto/data:Z
      - ./log:/mosquitto/log:Z
    environment:
      - TZ=Europe/Rome

